/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2023-12-03 09:29:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class story_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/project_DAY/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/day/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/project_DAY/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/day/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1698885481330L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/project_DAY/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/day/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write(' ');
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write(' ');
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("    \r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <meta name=\"description\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("        <title>D.A.Y 스토리</title>\r\n");
      out.write("        <!-- Favicon-->\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/favicon.ico\" />\r\n");
      out.write("        <!-- Font Awesome icons (free version)-->\r\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v6.3.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/story_styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("        \r\n");
      out.write("        <!-- font -->\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/Font.css\" rel=\"stylesheet\" />\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#book {\r\n");
      out.write("    margin: 2em auto;\r\n");
      out.write("    width: 800px;\r\n");
      out.write("    height: 600px; /* 높이가 이전에 400px로 되어 있었으나, 페이지 높이와 일치시키기 위해 600px로 수정 */\r\n");
      out.write("     overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#book .page {\r\n");
      out.write("    width: 400px; /* 책의 한 페이지 너비 */\r\n");
      out.write("    height: 600px; /* 책의 한 페이지 높이 */\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    border: 1px solid #cccccc;\r\n");
      out.write("    box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    background-size: cover; /* 추가된 스타일 */\r\n");
      out.write("    background-position: center center; /* 추가된 스타일 */\r\n");
      out.write("}\r\n");
      out.write(".nav-item.dropdown {\r\n");
      out.write("  position: relative; /* 드롭다운 버튼을 상대 위치로 설정합니다. */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("  position: absolute; /* 드롭다운 메뉴를 절대 위치로 설정합니다. */\r\n");
      out.write("  right: 0; /* 드롭다운 메뉴를 상위 요소의 오른쪽 끝에 맞춥니다. */\r\n");
      out.write("  left: auto; /* 기본적으로 왼쪽 정렬을 취소합니다. */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portfolio > div > div.text-center > p > strong {\r\n");
      out.write("   font-size: 1.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("span.span-interval {\r\n");
      out.write("    margin: 0 1em;\r\n");
      out.write("    color: #4141413d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.category_span {\r\n");
      out.write("   font-size: 1.1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#portfolio > div > div.text-center  a {\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* /* 클릭한 링크 색상 */\r\n");
      out.write("/* #portfolio > div > div.text-center a.clicked {\r\n");
      out.write("   color: tomato;\r\n");
      out.write("} */ */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".total-div {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-wrap: wrap;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    gap: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-div {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: 420px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    box-shadow: 0px 2px 8px rgba(0, 0, 0, 0.25);\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-div2 {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portfolio > img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content-div {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    padding: 16px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    background: white;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title-div {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #242424;\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    font-family: AppleSDGothicNeoB00;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    letter-spacing: 0.20px;\r\n");
      out.write("    word-wrap: break-word;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".etc-div {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".writer-div {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #363636;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-family: AppleSDGothicNeoB00;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    letter-spacing: 0.20px;\r\n");
      out.write("    word-wrap: break-word;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-div2 img {\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".scroll-to-top-button {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  bottom: 2em;\r\n");
      out.write("  right: 4em;\r\n");
      out.write("  display: none;\r\n");
      out.write("  background-color: #a9a9a9;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  z-index: 999; /* 다른 요소 위에 표시 */\r\n");
      out.write("  \r\n");
      out.write("  /* 호버 효과 스타일 */\r\n");
      out.write("  transition: background-color 0.3s ease-in-out, color 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".scroll-to-top-button:hover {\r\n");
      out.write("  background-color: #00315c; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top-div{\r\n");
      out.write("\tdisplay:flex;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("}\r\n");
      out.write("#top-img{\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("    width: 2.2em;\r\n");
      out.write("}\r\n");
      out.write("</style>        \r\n");
      out.write("        \r\n");
      out.write("    </head>\r\n");
      out.write("    <body id=\"page-top\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- Portfolio Grid-->\r\n");
      out.write("        <section class=\"page-section bg-light\" id=\"portfolio\">\r\n");
      out.write("           <button id=\"scrollToTopBtn\" class=\"scroll-to-top-button\">\r\n");
      out.write("\t           <span id=\"top-div\">\r\n");
      out.write("\t           \t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main/arrowup.png\" id=\"top-img\">\r\n");
      out.write("\t           </span>\r\n");
      out.write("           </button>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center story-category\">\r\n");
      out.write("                    <p>다양한 일상, 색다른 DAY를 만나보세요!</p>\r\n");
      out.write("                    <span class=\"category_span\"><a class=\"link_tab\" id = \"tag-1\" href=\"javascript:golife()\" onclick=\"changeColor('tag-1')\">라이프</a></span>\r\n");
      out.write("                    <span class=\"span-interval\"><strong>|</strong></span>\r\n");
      out.write("                    <span class=\"category_span\"><a class=\"link_tab\" id = \"tag-2\" href=\"javascript:travel()\" onclick=\"changeColor('tag-2')\">여행</a></span>\r\n");
      out.write("                    <span class=\"span-interval\"><strong>|</strong></span>\r\n");
      out.write("                    <span class=\"category_span\"><a class=\"link_tab\" id = \"tag-3\" href=\"javascript:culture()\" onclick=\"changeColor('tag-3')\">문화</a></span>\r\n");
      out.write("                    <span class=\"span-interval\"><strong>|</strong></span>\r\n");
      out.write("                    <span class=\"category_span\"><a class=\"link_tab\" id = \"tag-4\" href=\"javascript:it()\" onclick=\"changeColor('tag-4')\">IT</a></span>\r\n");
      out.write("                    <span class=\"span-interval\"><strong>|</strong></span>\r\n");
      out.write("                    <span class=\"category_span\"><a class=\"link_tab\" id = \"tag-5\" href=\"javascript:sport()\" onclick=\"changeColor('tag-5')\">스포츠</a></span>\r\n");
      out.write("                    <span class=\"span-interval\"><strong>|</strong></span>\r\n");
      out.write("                    <span class=\"category_span\"><a class=\"link_tab\" id = \"tag-6\" href=\"javascript:issue()\" onclick=\"changeColor('tag-6')\">시사</a></span>      \r\n");
      out.write("                </div>\r\n");
      out.write("                       \r\n");
      out.write("</div>     \r\n");
      out.write("                 </section>\r\n");
      out.write("                  <section class=\"bg-light sec-story\" id=\"portfolio\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("               <!-- 태그에 따른 글목록 -->\r\n");
      out.write("                <div class=\"scroll-container\" id=\"scroll-container\">\r\n");
      out.write("                   <div class=\"row\" id=\"view\">\r\n");
      out.write("   \r\n");
      out.write("                   </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Footer-->\r\n");
      out.write("        <footer class=\"footer py-4\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center\">                  \r\n");
      out.write("                    <div class=\"col-lg-4 my-3 my-lg-0\">\r\n");
      out.write("                       Copyright ⓒ 2023 D.A.Y Rights Reserved.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- 게시글 상세 모달 -->\r\n");
      out.write("        <!-- Portfolio item 1 modal popup-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("                <div class=\"modal-content modal-sm\"\">\r\n");
      out.write("                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/close-icon.svg\" alt=\"Close modal\" /></div>\r\n");
      out.write("                    <div id=\"modal-container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project details-->\r\n");
      out.write("                                    <div class=\"txt-div\">\r\n");
      out.write("                                    <ul class=\"txt-1\">\r\n");
      out.write("\t                                    <li id=\"stTitle\" class=\"text-uppercase\"></li>\r\n");
      out.write("\t                                    <li id=\"stDiary\"></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("<!--                                     <ul class=\"txt-2\">\r\n");
      out.write("\t                                    <li id=\"stNick\" class=\"item-intro text-muted\"></li>\r\n");
      out.write("                                    </ul>  -->                            \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"detail_story\">\r\n");
      out.write("\t                                    <img id=\"stImg\" class=\"img-fluid d-block mx-auto\" src=\"\" alt=\"...\" />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"modal-btn\">\r\n");
      out.write("\t                                    <a id=\"goblog\"><button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("\t                                       Go Blog\r\n");
      out.write("\t                                    </button></a>\r\n");
      out.write("\t                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("\t                                        <i class=\"fas fa-xmark me-1\"></i>\r\n");
      out.write("\t                                        Close\r\n");
      out.write("\t                                    </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/scripts.js\"></script>\r\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.startbootstrap.com/sb-forms-latest.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/turn_js/turn.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/turn_js/turn.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("    </body>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("        // HTML이 다 로딩되고나서 아래 코드실행\r\n");
      out.write("        golife();\r\n");
      out.write("     });\r\n");
      out.write("    \r\n");
      out.write("    function golife(){\r\n");
      out.write("        // 비동기방식으로 게시글 리스트 가져오기 기능\r\n");
      out.write("        // ajax - 요청 url, 어떻게 데이터 받을지, 요청방식 등... -> 객체\r\n");
      out.write("        $.ajax({\r\n");
      out.write("           url : \"board/golife\",\r\n");
      out.write("           type : \"get\",\r\n");
      out.write("           dataType : \"json\",\r\n");
      out.write("           success : makeView, // 콜백함수\r\n");
      out.write("           error : function() { alert(\"error\"); }\r\n");
      out.write("        });\r\n");
      out.write("     }\r\n");
      out.write("    function travel(){\r\n");
      out.write("        // 비동기방식으로 게시글 리스트 가져오기 기능\r\n");
      out.write("        // ajax - 요청 url, 어떻게 데이터 받을지, 요청방식 등... -> 객체\r\n");
      out.write("        $.ajax({\r\n");
      out.write("           url : \"board/travel\",\r\n");
      out.write("           type : \"get\",\r\n");
      out.write("           dataType : \"json\",\r\n");
      out.write("           success : makeView, // 콜백함수\r\n");
      out.write("           error : function() { alert(\"error\"); }\r\n");
      out.write("        });\r\n");
      out.write("     }\r\n");
      out.write("    function culture(){\r\n");
      out.write("        // 비동기방식으로 게시글 리스트 가져오기 기능\r\n");
      out.write("        // ajax - 요청 url, 어떻게 데이터 받을지, 요청방식 등... -> 객체\r\n");
      out.write("        $.ajax({\r\n");
      out.write("           url : \"board/culture\",\r\n");
      out.write("           type : \"get\",\r\n");
      out.write("           dataType : \"json\",\r\n");
      out.write("           success : makeView, // 콜백함수\r\n");
      out.write("           error : function() { alert(\"error\"); }\r\n");
      out.write("        });\r\n");
      out.write("     }\r\n");
      out.write("    function it(){\r\n");
      out.write("        // 비동기방식으로 게시글 리스트 가져오기 기능\r\n");
      out.write("        // ajax - 요청 url, 어떻게 데이터 받을지, 요청방식 등... -> 객체\r\n");
      out.write("        $.ajax({\r\n");
      out.write("           url : \"board/it\",\r\n");
      out.write("           type : \"get\",\r\n");
      out.write("           dataType : \"json\",\r\n");
      out.write("           success : makeView, // 콜백함수\r\n");
      out.write("           error : function() { alert(\"error\"); }\r\n");
      out.write("        });\r\n");
      out.write("     }\r\n");
      out.write("    function sport(){\r\n");
      out.write("        // 비동기방식으로 게시글 리스트 가져오기 기능\r\n");
      out.write("        // ajax - 요청 url, 어떻게 데이터 받을지, 요청방식 등... -> 객체\r\n");
      out.write("        $.ajax({\r\n");
      out.write("           url : \"board/sport\",\r\n");
      out.write("           type : \"get\",\r\n");
      out.write("           dataType : \"json\",\r\n");
      out.write("           success : makeView, // 콜백함수\r\n");
      out.write("           error : function() { alert(\"error\"); }\r\n");
      out.write("        });\r\n");
      out.write("     }\r\n");
      out.write("    function issue(){\r\n");
      out.write("        // 비동기방식으로 게시글 리스트 가져오기 기능\r\n");
      out.write("        // ajax - 요청 url, 어떻게 데이터 받을지, 요청방식 등... -> 객체\r\n");
      out.write("        $.ajax({\r\n");
      out.write("           url : \"board/issue\",\r\n");
      out.write("           type : \"get\",\r\n");
      out.write("           dataType : \"json\",\r\n");
      out.write("           success : makeView, // 콜백함수\r\n");
      out.write("           error : function() { alert(\"error\"); }\r\n");
      out.write("        });\r\n");
      out.write("     }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("     function makeView(data) {\r\n");
      out.write("\r\n");
      out.write("        var listHtml = \"\";\r\n");
      out.write("        data.forEach(function (obj) {\r\n");
      out.write("            listHtml += `\r\n");
      out.write("                <div class=\"col-lg-4 col-sm-6 mb-4\">\r\n");
      out.write("                    <div class=\"portfolio-item\">\r\n");
      out.write("                        <a class=\"portfolio-link\" id=\"story\" data-idx=\"${obj.bd_idx}\" data-bs-toggle=\"modal\" href=\"#portfolioModal1\" style=\"background-image:url('${obj.bd_content}')\">\r\n");
      out.write("                            <div class=\"portfolio-hover\">\r\n");
      out.write("                                <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"portfolio-caption\">\r\n");
      out.write("                            <div class=\"portfolio-caption-heading\">${obj.bd_title}</div>\r\n");
      out.write("                            <div class=\"portfolio-caption-subheading text-muted\">${obj.user_nick}</div>\r\n");
      out.write("                            <div class=\"portfolio-caption-subheading text-muted\">${new Date(obj.created_at).getFullYear() + '.' + ('0' + (new Date(obj.created_at).getMonth() + 1)).slice(-2) + '.' + ('0' + new Date(obj.created_at).getDate()).slice(-2)}</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>   \r\n");
      out.write("            `; \r\n");
      out.write("            \r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        $(\"#view\").html(listHtml);\r\n");
      out.write("    }  \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- /* 상단 스크롤 버튼 */ -->\r\n");
      out.write("    <script type=\"text/javascript\">    \r\n");
      out.write("     const scrollToTopButton = document.getElementById('scrollToTopBtn');\r\n");
      out.write("   \r\n");
      out.write("     // 스크롤 위치가 일정 값 이상일 때 버튼을 표시\r\n");
      out.write("     window.addEventListener('scroll', () => {\r\n");
      out.write("       if (window.scrollY > 200) { // 스크롤 위치 조건을 원하는 위치로 조정\r\n");
      out.write("         scrollToTopButton.style.display = 'block';\r\n");
      out.write("       } else {\r\n");
      out.write("         scrollToTopButton.style.display = 'none';\r\n");
      out.write("       }\r\n");
      out.write("     });\r\n");
      out.write("   \r\n");
      out.write("     // 버튼 클릭 시 페이지 맨 위로 스크롤\r\n");
      out.write("     scrollToTopButton.addEventListener('click', () => {\r\n");
      out.write("       window.scrollTo({\r\n");
      out.write("         top: 0,\r\n");
      out.write("         behavior: 'smooth' // 부드러운 스크롤 효과\r\n");
      out.write("       });\r\n");
      out.write("     });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- a 태그 색상 변경 -->\r\n");
      out.write("    <script type=\"text/javascript\">   \r\n");
      out.write("       function changeColor(category) {\r\n");
      out.write("           // 모든 링크의 색상을 초기화\r\n");
      out.write("           resetColors();\r\n");
      out.write("   \r\n");
      out.write("           // 클릭된 링크의 색상을 변경\r\n");
      out.write("\t\t\tdocument.getElementById(category).style.color = '#00315c';\r\n");
      out.write("\t\t\tdocument.getElementById(category).style.fontWeight = 'bolder';\r\n");
      out.write("\r\n");
      out.write("         }\r\n");
      out.write("   \r\n");
      out.write("         function resetColors() {\r\n");
      out.write("           // 모든 링크의 색상을 원래대로 되돌립니다.\r\n");
      out.write("           const categories = ['tag-1', 'tag-2', 'tag-3', 'tag-4', 'tag-5', 'tag-6'];\r\n");
      out.write("           categories.forEach(function (category) {\r\n");
      out.write("             document.getElementById(category).style.color = '';\r\n");
      out.write("             document.getElementById(category).style.fontWeight = 'normal';\r\n");
      out.write("           });\r\n");
      out.write("         }\r\n");
      out.write("         changeColor('tag-1');\r\n");
      out.write("         \r\n");
      out.write("         $(document).ready(function() {\r\n");
      out.write("               $('#portfolioModal1').on('show.bs.modal', function(event) {\r\n");
      out.write("                   var button = $(event.relatedTarget); // 클릭한 a 태그의 정보를 가져옴\r\n");
      out.write("                   var idx = button.data('idx'); // data-idx 속성 값을 가져옴\r\n");
      out.write("                   \r\n");
      out.write("\r\n");
      out.write("                   $.ajax({\r\n");
      out.write("                       url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/getmodal\",\r\n");
      out.write("                       data: {\"idx\": idx},\r\n");
      out.write("                       type: \"get\",\r\n");
      out.write("                       dataType: \"json\",\r\n");
      out.write("                       success: function(data) {\r\n");
      out.write("                           makeBoard(data, idx); // 여기서 makeBoard 호출\r\n");
      out.write("                       },\r\n");
      out.write("                       error: function(e) {\r\n");
      out.write("                           console.log(e);\r\n");
      out.write("                       }\r\n");
      out.write("                   });\r\n");
      out.write("               });\r\n");
      out.write("           });\r\n");
      out.write("\r\n");
      out.write("         function makeBoard(data, clickedIdx) {\r\n");
      out.write("               var bookContent = \"<div id='book'>\";\r\n");
      out.write("               bookContent += \"<div class='page'></div>\"; // 첫 페이지 추가\r\n");
      out.write("\t\t\t\t$('#goblog').attr(\"href\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/blog/\"+data[0].user_id);\r\n");
      out.write("               var startingPage = 1; // 시작 페이지 초기화\r\n");
      out.write("               var startingData;\r\n");
      out.write("               \r\n");
      out.write("               console.log(clickedIdx);\r\n");
      out.write("               data.forEach(function (item, index) {\r\n");
      out.write("                   // 각 페이지에 해당하는 이미지 추가\r\n");
      out.write("                   bookContent += `\r\n");
      out.write("                       <div class='page' style='background-image: url(${item.bd_content}); background-size: 200% 100%; background-position: left;'></div>\r\n");
      out.write("                       <div class='page' style='background-image: url(${item.bd_content}); background-size: 200% 100%; background-position: right;'></div>\r\n");
      out.write("                   `;\r\n");
      out.write("                   if (item.bd_idx === clickedIdx) {\r\n");
      out.write("                       startingPage = index * 2 + 2;\r\n");
      out.write("                       //console.log(index, startingPage);// 클릭한 게시글의 페이지 번호 계산\r\n");
      out.write("                       startingData = item;\r\n");
      out.write("                   }\r\n");
      out.write("               });\r\n");
      out.write("               bookContent += \"</div>\";\r\n");
      out.write("\r\n");
      out.write("               $('.detail_story').html(bookContent);\r\n");
      out.write("\r\n");
      out.write("               // turn.js 초기화 및 페이지 설정\r\n");
      out.write("               $('#book').turn({\r\n");
      out.write("                   width: 920,\r\n");
      out.write("                   height: 500,\r\n");
      out.write("                   autoCenter: true,\r\n");
      out.write("                   page: startingPage // 클릭한 게시글의 페이지로 시작\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("               // 시작 페이지에 해당하는 데이터로 제목, 닉네임, 다이어리 이름 업데이트\r\n");
      out.write("               if (startingData) {\r\n");
      out.write("                   $('#stTitle').text(startingData.bd_title);\r\n");
      out.write("                   $('#stNick').text(startingData.user_nick);\r\n");
      out.write("                   $('#stDiary').text(startingData.bd_diary);\r\n");
      out.write("               }\r\n");
      out.write("\r\n");
      out.write("               // 페이지가 넘어갈 때마다 업데이트\r\n");
      out.write("               $('#book').on(\"turning\", function(event, page, view) {\r\n");
      out.write("                   if (page === 1) {\r\n");
      out.write("                          event.preventDefault(); // 첫 페이지로 이동 시 이동을 취소\r\n");
      out.write("                      } else {\r\n");
      out.write("                          // 페이지가 넘어갈 때마다 업데이트\r\n");
      out.write("                          var currentPageData = data[Math.floor(page / 2) - 1];\r\n");
      out.write("                          $('#stTitle').text(currentPageData.bd_title);\r\n");
      out.write("                          $('#stNick').text(currentPageData.user_nick);\r\n");
      out.write("                          $('#stDiary').text(currentPageData.bd_diary);\r\n");
      out.write("                      }\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("               });\r\n");
      out.write("           }\r\n");
      out.write("         $(window).resize(function() {\r\n");
      out.write("             var width = $('#book').parent().width();\r\n");
      out.write("             var height = width * 0.75; // 가로세로 비율 유지\r\n");
      out.write("             $('#book').turn('size', width, height);\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/main/story.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cpath");
      // /WEB-INF/views/main/story.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/story.jsp(7,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/main/story.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("cimage");
      // /WEB-INF/views/main/story.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/story.jsp(8,0) '${pageContext.request.contextPath}/resources/content/'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}/resources/content/",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/main/story.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("awsPath");
      // /WEB-INF/views/main/story.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/story.jsp(9,0) 'https://daydayday.s3.ap-northeast-2.amazonaws.com/day'",_jsp_getExpressionFactory().createValueExpression("https://daydayday.s3.ap-northeast-2.amazonaws.com/day",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }
}
