/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2023-12-03 09:36:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.blog;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mydiary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/project_DAY/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/day/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/project_DAY/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/day/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1698885481330L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/project_DAY/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/day/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write(' ');
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<!--\r\n");
      out.write("   Read Only by HTML5 UP\r\n");
      out.write("   html5up.net | @ajlkn\r\n");
      out.write("   Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("      <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".DAY</title>\r\n");
      out.write("      <meta charset=\"utf-8\" />\r\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("       <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/Font.css\" rel=\"stylesheet\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main.css\" />\r\n");
      out.write("      \r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("     <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>   \r\n");
      out.write("   <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header.css\" rel=\"stylesheet\" />\r\n");
      out.write("   \r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  \r\n");
      out.write("  /* 사용자 지정 색 */\r\n");
      out.write("     :root {\r\n");
      out.write("        --sidebar-color: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_sidebar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("    } \r\n");
      out.write("\r\n");
      out.write("#mainNav {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  z-index: 10003;\r\n");
      out.write("  /* 추가 스타일링 */\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  height: 3.7em;\r\n");
      out.write("  padding-bottom: 1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav {\r\n");
      out.write("    flex-direction: row; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#header-col {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    margin: 0 1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul#goWrite {\r\n");
      out.write("    text-align: start;\r\n");
      out.write("    /* margin-left: 0.2em; */\r\n");
      out.write("    padding-left: 1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#header-col {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    width: 100%; \r\n");
      out.write("}\r\n");
      out.write(".log-cl{      \r\n");
      out.write("   border:none;\r\n");
      out.write("    padding: 6px 13px 6px 13px;\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  padding-top: 3.7em; /* 헤더 높이만큼 패딩을 주어 내용이 헤더에 가려지지 않도록 함 */\r\n");
      out.write("}\r\n");
      out.write("#blog-nav {\r\n");
      out.write("    font-size: 1.5em;\r\n");
      out.write("}\r\n");
      out.write("  </style>\r\n");
      out.write("  \r\n");
      out.write("   </head>\r\n");
      out.write("   <body class=\"is-preload\" style=\"background-color:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- 상단 헤더 -->\r\n");
      out.write("     <nav class=\"navbar navbar-expand-lg navbar-dark fixed-top\" id=\"mainNav\">\r\n");
      out.write("        <div class=\"top-nav\" id=\"header-col\">\r\n");
      out.write("               <ul class=\"navbar-nav text-uppercase ms-auto py-4 py-lg-0\" id=\"nav-head\">\r\n");
      out.write("                   <li class=\"nav-item\"><a class=\"navbar-brand\" id=\"blog-nav\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">D.A.Y</a></li>\r\n");
      out.write("                   ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                   <li class=\"nav-item rg\"><a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/story\">스토리</a></li>                \r\n");
      out.write("                  ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group position-relative\" id=\"diary-search\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"search\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/search.png\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"searchInput\" type=\"text\" class=\"rounded custom-width\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Search\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"searchResults\" class=\"position-absolute\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>                  \r\n");
      out.write("               </ul>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <div class=\"log-div\">\r\n");
      out.write("                   <ul class=\"navbar-nav text-uppercase ms-auto py-4 py-lg-0\" id=\"log-ul\">\r\n");
      out.write("                     ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                     ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                   </ul>\r\n");
      out.write("                </div>   \r\n");
      out.write("        </div>\r\n");
      out.write("       <!-- 네비게이션 내용 -->\r\n");
      out.write("     </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <div id=\"allDiv\">\r\n");
      out.write("\r\n");
      out.write("   <!-- 사이드바 -->\r\n");
      out.write("         <section id=\"header\" style=\"background-color:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_sidebar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\" class=\"blog-sidebar\">\r\n");
      out.write("            <header>\r\n");
      out.write("               <span class=\"image avatar\">\r\n");
      out.write("               <div class=\"profileDiv\"><img id=\"profileImg\" class=\"img-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_profile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\" /></div>\r\n");
      out.write("\r\n");
      out.write("               </span>\r\n");
      out.write("               <h1 id=\"logo\"><a href=\"#\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.user_nick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></h1>\r\n");
      out.write("                     <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_greetings }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("            </header>\r\n");
      out.write("            <nav id=\"nav\">\r\n");
      out.write("               <ul>\r\n");
      out.write("                  <li><a href=\"#one\" class=\"section-link active\" data-section=\"diary\">다이어리</a></li>\r\n");
      out.write("                  <li><a href=\"#two\" class=\"section-link\" data-section=\"guestBook\">방명록</a></li>\r\n");
      out.write("                  <!--  <li><a href=\"#three\" class=\"section-link\" data-section=\"tempStorage\">임시보관함</a></li> -->\r\n");
      out.write("                  <!--");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write(" -->\r\n");
      out.write("                     <li><a href=\"#four\" class=\"section-link\" data-section=\"blogSetting\">블로그 관리</a></li>\r\n");
      out.write("                  \r\n");
      out.write("               </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("          \r\n");
      out.write("            <footer>\r\n");
      out.write("               <ul class=\"icons\">\r\n");
      out.write("                  <li><span class=\"label\">Copyright ⓒ 2023 D.A.Y Rights Reserved.</span></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </footer>\r\n");
      out.write("         </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Wrapper -->\r\n");
      out.write("         <div id=\"wrapper\" style=\"background-color:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Main -->\r\n");
      out.write("               \r\n");
      out.write("          <!-- header 이미지 -->\r\n");
      out.write("            <div id=\"main-head\">\r\n");
      out.write("               <div class=\"image main\" data-position=\"center\">\r\n");
      out.write("                     <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_header}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\" />\r\n");
      out.write("                     <p class=\"imgText\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("            <div id=\"main\">\r\n");
      out.write("                     <!-- 다이어리 -->\r\n");
      out.write("                   <div class=\"container\" id=\"diary\">\r\n");
      out.write("                     <h3>MY DIARY</h3>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                       <div class=\"btnClass\">\r\n");
      out.write("                    <button class=\"group-3\" id=\"goEdit\" data-toggle=\"modal\" type=\"button\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/edit/in'\" >\r\n");
      out.write("                        <div class=\"group-4\">\r\n");
      out.write("                          <img class=\"img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/goWrite.png\" />\r\n");
      out.write("                          <div class=\"text-wrapper-4\">WRITE</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </button>                  \r\n");
      out.write("                    <button class=\"group-3\" onclick=\"makediary();\"id=\"goEdit\" data-toggle=\"modal\" data-target=\"#makeDiary\">\r\n");
      out.write("                        <div class=\"group-4\">\r\n");
      out.write("                          <img class=\"img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/diary_add.png\" />\r\n");
      out.write("                          <div class=\"text-wrapper-4\">MAKE</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </button>                  \r\n");
      out.write("                       </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <div id=\"diaryContainer\">\r\n");
      out.write("                  <ul class=\"thumblist\">\r\n");
      out.write("                     ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("            <!-- 글쓰기(방명록) 작성 폼 -->\r\n");
      out.write("            <div class=\"modal fade\" id=\"makeDiary\">\r\n");
      out.write("               <div class=\"modal-container modal-dialog modal-dialog-centered\">\r\n");
      out.write("                  <div class=\"modal-content\">\r\n");
      out.write("                     <!-- Modal Header -->\r\n");
      out.write("                     <div class=\"modalHeader\">\r\n");
      out.write("                        <h4 class=\"modal-title\"></h4>\r\n");
      out.write("                        <button type=\"button\" class=\"btn\" data-dismiss=\"modal\"><img class=\"closeModal\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/close.png\"></button>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <!-- Modal body -->\r\n");
      out.write("                     <div class=\"modal-body\">\r\n");
      out.write("                        <form id=\"diaryModal\" action=\"\" method=\"post\">\r\n");
      out.write("                           \r\n");
      out.write("                              <!--  로그인한 회원 아이디 정보도 함께 보내주기 for 회원제 게시판 -->\r\n");
      out.write("                           <input type=\"hidden\" name=\"user_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                           <table class=\"modalContent\">\r\n");
      out.write("                                 <tr>\r\n");
      out.write("                                    <td colspan=\"3\"><input id=\"diarytitle\" type=\"text\" name=\"diary_name\" placeholder=\"다이어리 제목을 입력하세요.\"></td>\r\n");
      out.write("                                 </tr>\r\n");
      out.write("                                 <tr>\r\n");
      out.write("                                    <td><input class=\"coverPick\" id=\"cover1\" type=\"radio\" name=\"diary_cover\" value=\"cover1.jpg\">\r\n");
      out.write("                                    <label for=\"cover1\"><img class=\"cover\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cover/cover1.jpg\"></label></td>\r\n");
      out.write("                                 \r\n");
      out.write("                                    <td><input class=\"coverPick\" id=\"cover2\" type=\"radio\" name=\"diary_cover\" value=\"cover2.jpg\">\r\n");
      out.write("                                    <label for=\"cover2\"><img class=\"cover\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cover/cover2.jpg\"></label></td>\r\n");
      out.write("                                 \r\n");
      out.write("                                    <td><input class=\"coverPick\" id=\"cover3\" type=\"radio\" name=\"diary_cover\" value=\"cover3.jpg\">\r\n");
      out.write("                                    <label for=\"cover3\"><img class=\"cover\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cover/cover3.jpg\"></label></td>\r\n");
      out.write("                                 \r\n");
      out.write("                                    <td><input class=\"coverPick\" id=\"cover4\" type=\"radio\" name=\"diary_cover\" value=\"cover4.jpg\">\r\n");
      out.write("                                    <label for=\"cover4\"><img class=\"cover\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cover/cover4.jpg\"></label></td>\r\n");
      out.write("                                 \r\n");
      out.write("                                    <td><input class=\"coverPick\" id=\"cover5\" type=\"radio\" name=\"diary_cover\" value=\"cover5.jpg\">\r\n");
      out.write("                                    <label for=\"cover5\"><img class=\"cover\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cover/cover5.jpg\"></label></td>\r\n");
      out.write("                                 </tr>\r\n");
      out.write("                                    \r\n");
      out.write("                           </table>\r\n");
      out.write("                           <div class=\"modalFooter\">\r\n");
      out.write("                              <input class=\"btn btn-sm btn-defalut\" type=\"submit\" value=\"확인\">\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- 방명록 -->\r\n");
      out.write("         <div class=\"container\" id=\"guestBook\">\r\n");
      out.write("            <h3>방명록</h3>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div id=\"visitList\"></div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <!-- 다이어리 상세페이지 -->\r\n");
      out.write("                        <div class=\"container\" id=\"tempStorage\">\r\n");
      out.write("                          <div class=\"book-header\">\r\n");
      out.write("                              <p id=\"diaryName\"></p>\r\n");
      out.write("                             <div class=\"row-header\">\r\n");
      out.write("                              <p id=\"boardTitle\"></p>\r\n");
      out.write("                              <div class=\"back-btn\"><a id=\"mainbtn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myblog/in\" class=\"button\">목록</a></div>\r\n");
      out.write("                             </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                           <div id=\"book\" class=\"features\">\r\n");
      out.write("                               \r\n");
      out.write("                           </div>\r\n");
      out.write("                              \r\n");
      out.write("                           <div id=\"pagination\">\r\n");
      out.write("                              <button class=\"pagebtn\" onclick=\"changePage('prev')\"><img id=\"prev-btn\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/left-dark.png\"></button>\r\n");
      out.write("                                <!--   <span id=\"current-page\">1</span> / <span id=\"total-pages\"></span> -->\r\n");
      out.write("                              <button class=\"pagebtn\" onclick=\"changePage('next')\"><img id=\"next-btn\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/right-dark.png\"></button>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <!-- 블로그 관리 -->\r\n");
      out.write("                        <div class=\"container\" id=\"blogSetting\">\r\n");
      out.write("                          <div class=\"formDiv\">\r\n");
      out.write("                           <h3>블로그 관리</h3>\r\n");
      out.write("                           <hr>\r\n");
      out.write("                           <!-- <p>Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer. Integer eu ante ornare amet commetus.</p> -->\r\n");
      out.write("                           <div id=\"form-content\">\r\n");
      out.write("                              <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myblog/blogUpdate\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                                 <!--  <div class=\"row gtr-uniform\"> -->\r\n");
      out.write("                                 <input type=\"hidden\" name=\"user_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                    <table class=\"table\">\r\n");
      out.write("                                       <tr>\r\n");
      out.write("                                          <th>프로필 사진</th>\r\n");
      out.write("                                          <td id=\"profile-div\">\r\n");
      out.write("                                             <div class=\"imgDiv\"><img id =\"profile\" class=\"img-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_profile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></div>\r\n");
      out.write("                                             <div class=\"inputDiv\">\r\n");
      out.write("                                                <label for=\"blog_profile\" class=\"input-btn\">사진변경</label>\r\n");
      out.write("                                                <input type=\"file\" accept=\"image/*\" id=\"blog_profile\" name=\"blog_profile\" onchange=\"readProfile(this)\" style=\"display:none;\">\r\n");
      out.write("                                                <label for=\"profileReset\" class=\"input-btn\">삭제</label>\r\n");
      out.write("                                                <input type=\"reset\" id=\"profileReset\" style=\"display:none;\"/>\r\n");
      out.write("                                             </div>                                             \r\n");
      out.write("                                          </td>\r\n");
      out.write("                                       </tr>\r\n");
      out.write("                                     \r\n");
      out.write("                                       <tr>\r\n");
      out.write("                                          <th>블로그 제목</th>\r\n");
      out.write("                                          <td><input type=\"text\" name=\"blog_title\" id=\"blog_title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("                                       </tr>\r\n");
      out.write("                                       <tr>\r\n");
      out.write("                                          <th>소개글</th>\r\n");
      out.write("                                          <td><input type=\"text\" name=\"blog_greetings\" id=\"blog_intro\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_greetings}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("                                       </tr>\r\n");
      out.write("                                       <tr>\r\n");
      out.write("                                          <th>헤더</th>\r\n");
      out.write("                                          <td>\r\n");
      out.write("                                             <div class=\"imgDiv\"><img id =\"blogHeader\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_header}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <br>\r\n");
      out.write("                                             <div class=\"headerDiv\">\r\n");
      out.write("                                                <label for=\"blog_header\" class=\"input-btn\">사진변경</label>\r\n");
      out.write("                                                <input type=\"file\" accept=\"image/*\" id=\"blog_header\" name=\"blog_header\" onchange=\"readHeader(this)\" style=\"display:none;\">\r\n");
      out.write("                                                <label for=\"headerReset\" class=\"input-btn\">삭제</label>\r\n");
      out.write("                                                <input type=\"reset\" id=\"headerReset\" style=\"display:none;\"/>\r\n");
      out.write("                                             </div>\r\n");
      out.write("                                             </div>                                                \r\n");
      out.write("                                          </td>\r\n");
      out.write("                                       </tr>\r\n");
      out.write("                                       <tr>\r\n");
      out.write("                                          <th>사이드바</th>\r\n");
      out.write("                                          <td><div class=\"color\"><input type=\"color\" id=\"blog_side\" name=\"blog_sidebar\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_sidebar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></div></td>\r\n");
      out.write("                                       </tr>\r\n");
      out.write("                                       <tr>\r\n");
      out.write("                                          <th>배경</th>\r\n");
      out.write("                                          <td><div class=\"color\"><input type=\"color\" id=\"blog_body\" name=\"blog_main\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></div></td>\r\n");
      out.write("                                       </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                     <div class=\"btnGroup\">\r\n");
      out.write("                                          <input class = \"blogbtn\" type=\"submit\" value=\"수정\">\r\n");
      out.write("                                          <input type=\"reset\" value=\"취소\">\r\n");
      out.write("                                       </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                   </form>\r\n");
      out.write("                                 </div>            \r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Scripts -->\r\n");
      out.write("         <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.min.js\"></script>\r\n");
      out.write("         <!-- <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("         <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.scrolly.min.js\"></script> -->\r\n");
      out.write("         <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/browser.min.js\"></script>\r\n");
      out.write("         <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/breakpoints.min.js\"></script>\r\n");
      out.write("         <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/util.js\"></script>\r\n");
      out.write("         <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("         <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/turn_js/turn.min.js\"></script>\r\n");
      out.write("       <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/turn_js/turn.js\"></script>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("window.addEventListener(\"load\", function() {\r\n");
      out.write("    let content = document.querySelector(\"#header > header\");\r\n");
      out.write("\r\n");
      out.write("    // 스크롤 이벤트 감지\r\n");
      out.write("    window.addEventListener(\"scroll\", function() {\r\n");
      out.write("        if (window.scrollY > 0) {\r\n");
      out.write("            // 스크롤을 내린 경우, margin-top을 0으로 설정\r\n");
      out.write("            content.style.marginTop = \"0\";\r\n");
      out.write("        } else {\r\n");
      out.write("            // 스크롤을 맨 위로 올린 경우, 초기 margin-top 값으로 설정\r\n");
      out.write("            content.style.marginTop = \"3.7em\";\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>       \r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("<script>\r\n");
      out.write("var book = $(\"#book\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function () {\r\n");
      out.write("    const sectionLinks = document.querySelectorAll('.section-link');\r\n");
      out.write("    const containers = document.querySelectorAll('.container');\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    containers.forEach(container => {\r\n");
      out.write("        if (container.id === 'diary') {\r\n");
      out.write("            container.style.display = 'block';\r\n");
      out.write("        } else {\r\n");
      out.write("            container.style.display = 'none';\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    // 초기에 diary만 보이게 설정하고, 다이어리 초기화\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    sectionLinks.forEach(link => {\r\n");
      out.write("        link.addEventListener('click', function (e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            const targetContainerId = link.getAttribute('data-section');\r\n");
      out.write("\r\n");
      out.write("            // 모든 container를 숨김\r\n");
      out.write("            containers.forEach(container => {\r\n");
      out.write("                container.style.display = 'none';\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // 클릭한 링크의 data-section 값을 가져와 해당 container를 표시\r\n");
      out.write("            const targetContainer = document.getElementById(targetContainerId);\r\n");
      out.write("\r\n");
      out.write("            if (targetContainer) {\r\n");
      out.write("                targetContainer.style.display = 'block';\r\n");
      out.write("            \r\n");
      out.write("                if (targetContainerId === 'diary') {\r\n");
      out.write("                    location.reload();\r\n");
      out.write("                }\r\n");
      out.write("               \r\n");
      out.write("             \r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function makediary(){\r\n");
      out.write("   $(\"#diaryModal\").attr(\"action\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myblog/makediary\");\r\n");
      out.write("    $(\".modal-title\").text(\"내 다이어리 만들기\");\r\n");
      out.write("    $(\"#diaryidx\").remove();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function modify(idx){\r\n");
      out.write("    \r\n");
      out.write("      console.log(idx);\r\n");
      out.write("      \r\n");
      out.write("      $(\"#diaryModal\").attr(\"action\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myblog/modifydiary\");\r\n");
      out.write("      $(\".modal-title\").text(\"내 다이어리 수정\");\r\n");
      out.write("      var newInput = $(\"<input>\").attr({\r\n");
      out.write("         id:\"diaryidx\",\r\n");
      out.write("           type: \"hidden\",\r\n");
      out.write("           name: \"diary_idx\",\r\n");
      out.write("           value: idx\r\n");
      out.write("       });\r\n");
      out.write("      $(\"#diaryModal\").append(newInput);\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   function getBoard(idx) {\r\n");
      out.write("       console.log(idx);\r\n");
      out.write("       \r\n");
      out.write("       $.ajax({\r\n");
      out.write("           url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/getBoard\",\r\n");
      out.write("           data: {\"idx\": idx},\r\n");
      out.write("           type: \"get\",\r\n");
      out.write("           dataType: \"json\",\r\n");
      out.write("           success: makeBoard,\r\n");
      out.write("           error: function(e) {\r\n");
      out.write("               console.log(e);\r\n");
      out.write("           }\r\n");
      out.write("       });\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   function getBoard(idx) {\r\n");
      out.write("       console.log(idx);\r\n");
      out.write("       \r\n");
      out.write("       $.ajax({\r\n");
      out.write("           url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/getBoard\",\r\n");
      out.write("           data: {\"idx\": idx},\r\n");
      out.write("           type: \"get\",\r\n");
      out.write("           dataType: \"json\",\r\n");
      out.write("           success: makeBoard,\r\n");
      out.write("           error: function(e) {\r\n");
      out.write("               console.log(e);\r\n");
      out.write("           }\r\n");
      out.write("       });\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function makeBoard(data) {\r\n");
      out.write("      console.log(data);\r\n");
      out.write("       var listHtml = \"\";\r\n");
      out.write("       $(\"#diaryName\").text(data[0].bd_diary);\r\n");
      out.write("       $(\"#boardTitle\").text(data[0].bd_title);\r\n");
      out.write("       // 첫 페이지 (표지)는 비워둡니다.\r\n");
      out.write("       listHtml += \"<div class='page'></div>\";\r\n");
      out.write("       // 두 번째 데이터 항목부터 이미지를 표시합니다.\r\n");
      out.write("       $.each(data, function(index, obj) {\r\n");
      out.write("     \r\n");
      out.write("           listHtml += \"<div class='page' style='background-image: url(\" + obj.bd_content + \"); background-size: 200% 100%; background-position: left;'>\";\r\n");
      out.write("           listHtml += \"</div>\"; // 왼쪽 면\r\n");
      out.write("\r\n");
      out.write("           listHtml += \"<div class='page' style='background-image: url(\" + obj.bd_content + \"); background-size: 200% 100%; background-position: right;'>\";\r\n");
      out.write("           listHtml += \"</div>\"; // 오른쪽 면\r\n");
      out.write("       });\r\n");
      out.write("       book.html(listHtml);\r\n");
      out.write("\r\n");
      out.write("    // turn.js를 사용하여 책 넘기기 효과 초기화\r\n");
      out.write("    book.turn({\r\n");
      out.write("                   width: '100%',\r\n");
      out.write("                   height: 600,\r\n");
      out.write("                   autoCenter: true,\r\n");
      out.write("                   gradients: true,\r\n");
      out.write("                   page:2\r\n");
      out.write("               }).on(\"turning\", function(event, page, view) {\r\n");
      out.write("                   // 페이지가 넘어갈 때마다 제목, 닉네임, 다이어리 이름 업데이트\r\n");
      out.write("                   if (page === 1) {\r\n");
      out.write("                           event.preventDefault(); // 첫 페이지로 이동 시 이동을 취소\r\n");
      out.write("                       }else if(page >1){\r\n");
      out.write("                         var currentPageData = data[Math.floor(page/2)-1]; // 페이지 인덱스를 데이터 인덱스로 변환\r\n");
      out.write("                         //console.log(data);\r\n");
      out.write("                         //console.log(page, currentPageData);\r\n");
      out.write("                        \r\n");
      out.write("                         $('#boardTitle').text(currentPageData.bd_title);\r\n");
      out.write("                         $('#boardTitle').show();\r\n");
      out.write("                         $('#book').addClass(\"book-shadow\");\r\n");
      out.write("                  } else {\r\n");
      out.write("                      $('#boardTitle').hide();\r\n");
      out.write("                  }\r\n");
      out.write("                  /* $(\".page\").addClass(\"page-flipping\"); */\r\n");
      out.write("               \r\n");
      out.write("               });\r\n");
      out.write("    \r\n");
      out.write("    // 현재 페이지 업데이트\r\n");
      out.write("    //updateCurrentPage(book.turn('page'));\r\n");
      out.write("\r\n");
      out.write("    // 총 페이지 수 업데이트\r\n");
      out.write("    //updateTotalPages(book.turn('pages'));\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* function updateCurrentPage(pageNumber) {\r\n");
      out.write("     document.getElementById('current-page').textContent = pageNumber;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   function updateTotalPages(totalPages) {\r\n");
      out.write("     document.getElementById('total-pages').textContent = totalPages;\r\n");
      out.write("   }  */\r\n");
      out.write("\r\n");
      out.write("// 페이지 변경 함수\r\n");
      out.write("   function changePage(direction) {\r\n");
      out.write("     // 현재 페이지와 총 페이지 수를 가져옴\r\n");
      out.write("     var currentPage = book.turn('page');\r\n");
      out.write("     console.log(\"currentPage\",currentPage);\r\n");
      out.write("     var totalPages = book.turn('pages');\r\n");
      out.write("     console.log(\"totalPages\",totalPages);\r\n");
      out.write("     \r\n");
      out.write("     if (direction === 'prev' && currentPage > 3) {\r\n");
      out.write("          book.turn('previous');\r\n");
      out.write("     } else if (direction === 'next' && currentPage < totalPages) {\r\n");
      out.write("       book.turn('next');\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     // 페이지 변경 후 현재 페이지 업데이트\r\n");
      out.write("     //updateCurrentPage(book.turn('page'));\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("// 초기 페이지 설정 (페이지 로딩 시 실행)\r\n");
      out.write("   document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("     // 초기 페이징 정보 업데이트\r\n");
      out.write("     if (book.turn('pages')) { // 'book'이 이미 초기화되었다면\r\n");
      out.write("       //updateTotalPages(book.turn('pages'));\r\n");
      out.write("       //updateCurrentPage(book.turn('page'));\r\n");
      out.write("     }\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   // 블로그 관리 - 프로필 사진 미리보기\r\n");
      out.write("   function readProfile(input) {\r\n");
      out.write("        if (input.files && input.files[0]) {\r\n");
      out.write("          var reader = new FileReader();\r\n");
      out.write("          reader.onload = function(e) {\r\n");
      out.write("            document.getElementById('profile').src = e.target.result;\r\n");
      out.write("          };\r\n");
      out.write("          reader.readAsDataURL(input.files[0]);\r\n");
      out.write("                  \r\n");
      out.write("        } else {\r\n");
      out.write("          document.getElementById('profile').src = \"\";\r\n");
      out.write("        }       \r\n");
      out.write("      }\r\n");
      out.write("    \r\n");
      out.write("// 삭제 버튼을 눌렀을 때 미리보기 이미지를 지우고 파일 입력 필드를 초기화합니다.\r\n");
      out.write("   document.getElementById('profileReset').addEventListener('click', function() {\r\n");
      out.write("     document.getElementById('profile').src = \"\";\r\n");
      out.write("     document.getElementById('blog_profile').value = \"\"; // 파일 입력 필드 초기화\r\n");
      out.write("   });         \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("   function readHeader(input) {\r\n");
      out.write("       if (input.files && input.files[0]) {\r\n");
      out.write("         var reader = new FileReader();\r\n");
      out.write("         reader.onload = function(e) {\r\n");
      out.write("           document.getElementById('blogHeader').src = e.target.result;\r\n");
      out.write("         };\r\n");
      out.write("         reader.readAsDataURL(input.files[0]);\r\n");
      out.write("       } else {\r\n");
      out.write("         document.getElementById('blogHeader').src = \"\";\r\n");
      out.write("       }\r\n");
      out.write("     }\r\n");
      out.write("  \r\n");
      out.write("     // 삭제 버튼을 눌렀을 때 미리보기 헤더 이미지를 지우고 파일 입력 필드를 초기화합니다.\r\n");
      out.write("       document.getElementById('headerReset').addEventListener('click', function() {\r\n");
      out.write("         document.getElementById('blogHeader').src = \"\";\r\n");
      out.write("         document.getElementById('blog_header').value = \"\"; // 파일 입력 필드 초기화\r\n");
      out.write("       });         \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    // 방명록 띄우기\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("      // 페이지가 열릴 때 바로 실행되게 만들어주기\r\n");
      out.write("      // HTML이 다 로딩되고나서 아래 코드 실행해라\r\n");
      out.write("      loadList();\r\n");
      out.write("      \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    function loadList(){\r\n");
      out.write("       // 비동기 방식으로 게시글 리스트 가져오기\r\n");
      out.write("       // ajax : 요청URL, 어떻게 데이터 받을지, 요청방식 등 ... -> 객체형태로 : {}(JSON 형식)\r\n");
      out.write("       // success 시 함수(makeView)를 실행 : ajax로 요청하고 나서 결과를 받아와서 끝나고(돌아와서) 실행하는 함수 -> 콜백함수\r\n");
      out.write("       var id = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("       \r\n");
      out.write("       //console.log(id);\r\n");
      out.write("       $.ajax({\r\n");
      out.write("          url :\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myblog/getVisit\",\r\n");
      out.write("          data : {\"id\":id},\r\n");
      out.write("          type :\"get\",\r\n");
      out.write("          dataType :\"json\",\r\n");
      out.write("          success : makeView,  // 콜백함수\r\n");
      out.write("          error : function(e){\r\n");
      out.write("             console.log(e);\r\n");
      out.write("          }\r\n");
      out.write("       });\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("    function makeView(data){\r\n");
      out.write("        var   listHtml = \"\";\r\n");
      out.write("        \r\n");
      out.write("        $.each(data, function(index, obj){\r\n");
      out.write("           listHtml += \"<div class='Card img-fluid post' style='width:300px'>\";\r\n");
      out.write("           listHtml += \"<img class='card-img-top imgCard' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/postit.png' alt='Card image' style='width:100%'>\";\r\n");
      out.write("           listHtml += \"<div class='card-img-overlay guestbook-card'>\";\r\n");
      out.write("            listHtml += \"<h4 class='card-title title guestbook-title'>\" +obj.user_nick + \"</h4>\";\r\n");
      out.write("            listHtml += \"<p class='card-text guestbook-text'>\" + obj.gb_content + \"</p>\";\r\n");
      out.write("            listHtml += \"<br>\";\r\n");
      out.write("            listHtml += \"<p class='indate'>\"+obj.created_at + \"</p>\";\r\n");
      out.write("            listHtml += \"<a href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/blog/\"+obj.guest+\"' class='btn btn-sm btn-defalut goGuestBlog-a' style='border:solid 0.5px #dfdfdf;'>구경가기</a>\";\r\n");
      out.write("            listHtml += \"</div></div>\";\r\n");
      out.write("           \r\n");
      out.write("        });\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("      $(\"#visitList\").html(listHtml);\r\n");
      out.write("      \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 사용자 지정색에 따른 블로그 폰트 색상 변경 -->         \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/* 배경 */\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    var bgColor = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("    var color = hexToRgb(bgColor);\r\n");
      out.write("    var brightness = (color.r * 299 + color.g * 587 + color.b * 114) / 1000;\r\n");
      out.write("    var textColor = brightness < 128 ? 'white' : 'rgb(49 49 49)';\r\n");
      out.write("    if(brightness < 128){\r\n");
      out.write("       $(\"hr\").css({\r\n");
      out.write("          \"background-color\": \"white\",\r\n");
      out.write("            \"height\": \"0.1px\"\r\n");
      out.write("       });\r\n");
      out.write("    }\r\n");
      out.write("    // 모든 .title 요소를 선택하고 스타일 적용\r\n");
      out.write("    document.querySelectorAll('#diaryContainer .area_text .title').forEach(function(element) {\r\n");
      out.write("        element.style.color = textColor;\r\n");
      out.write("    });\r\n");
      out.write("    document.querySelectorAll('#tempStorage p').forEach(function(element) {\r\n");
      out.write("        element.style.color = textColor;\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    document.querySelectorAll('#diary h3, #guestBook h3, #guestBook h6, #diary h6, #blogSetting h3').forEach(function(element) {\r\n");
      out.write("        element.style.color = textColor;\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    // 페이지 버튼 변경\r\n");
      out.write("    var prevImg = document.getElementById('prev-btn');\r\n");
      out.write("    var nextImg = document.getElementById('next-btn');\r\n");
      out.write("    if(brightness < 128) {\r\n");
      out.write("        prevImg = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/left-white.png\";\r\n");
      out.write("        nextImg = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/right-white.png\";\r\n");
      out.write("     }else{\r\n");
      out.write("        prevImg = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/left-dark.png\";\r\n");
      out.write("        nextImg = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/right-dark.png\";\r\n");
      out.write("     }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("/* 사이드바 */\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    var bgColor = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myblog.blog_sidebar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("    var color = hexToRgb(bgColor);\r\n");
      out.write("    var brightness = (color.r * 299 + color.g * 587 + color.b * 114) / 1000;\r\n");
      out.write("    var textColor = brightness < 220 ? 'white' : 'rgb(95, 95, 95)';\r\n");
      out.write("\r\n");
      out.write("    var navItems = document.querySelectorAll('#header > nav ul li');\r\n");
      out.write("    \r\n");
      out.write("    if (bgColor === '#ffffff') {\r\n");
      out.write("        var activeLinks = document.querySelectorAll('#header > nav ul li a.active');\r\n");
      out.write("\r\n");
      out.write("        activeLinks.forEach(function(link) {\r\n");
      out.write("            link.style.backgroundColor = 'rgb(95, 95, 95)';\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    document.querySelectorAll('#header h1 a, #header > header p, #header > nav ul li a:not(.active), #header > footer .icons li').forEach(function(element) {\r\n");
      out.write("        element.style.color = textColor;\r\n");
      out.write("        \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    // 모든 nav 항목에 대한 클릭 이벤트 리스너 설정\r\n");
      out.write("    navItems.forEach(function(item) {\r\n");
      out.write("        item.addEventListener('click', function() {\r\n");
      out.write("            // 모든 링크를 기본 색상으로 재설정\r\n");
      out.write("            navItems.forEach(function(otherItem) {\r\n");
      out.write("                var otherLink = otherItem.querySelector('a');\r\n");
      out.write("                \r\n");
      out.write("                if (bgColor){\r\n");
      out.write("                  otherLink.style.backgroundColor = bgColor;                   \r\n");
      out.write("                    otherLink.style.color = textColor;\r\n");
      out.write("                    otherLink.style.fontWeight = 'normal';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // 현재 클릭된 항목의 링크 색상을 변경\r\n");
      out.write("            var link = item.querySelector('a');\r\n");
      out.write("            if (link) {\r\n");
      out.write("                link.style.color = bgColor;\r\n");
      out.write("                link.style.fontWeight = 'bold';\r\n");
      out.write("                \r\n");
      out.write("               if (bgColor === '#ffffff'){\r\n");
      out.write("                   // 사이드바 색상 white일 경우\r\n");
      out.write("                  link.style.backgroundColor = 'rgb(95, 95, 95)';\r\n");
      out.write("               }else{\r\n");
      out.write("                   link.style.backgroundColor = 'white';\r\n");
      out.write("                  \r\n");
      out.write("               }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function hexToRgb(hex) {\r\n");
      out.write("    var bigint = parseInt(hex.slice(1), 16);\r\n");
      out.write("    var r = (bigint >> 16) & 255;\r\n");
      out.write("    var g = (bigint >> 8) & 255;\r\n");
      out.write("    var b = bigint & 255;\r\n");
      out.write("\r\n");
      out.write("    return { r, g, b };\r\n");
      out.write("}\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $('#searchInput').on('keyup', function() {\r\n");
      out.write("        var searchTerm = $(this).val();\r\n");
      out.write("        if (searchTerm.length > 0) {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/findId',\r\n");
      out.write("                data: { term: searchTerm },\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("                    $('#searchResults').empty();\r\n");
      out.write("                    $.each(data, function(index, dayBlog) {\r\n");
      out.write("                        var blogLink = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/blog/' + dayBlog.user_id;\r\n");
      out.write("                        var displayDiv = '<div class=\"search-result\"><a href=\"' + blogLink + '\"><img src=\"' + dayBlog.blog_profile + '\" alt=\"Profile Image\"> ' + dayBlog.user_id + '</a></div>';\r\n");
      out.write("                        $('#searchResults').append(displayDiv);\r\n");
      out.write("                    });\r\n");
      out.write("                },\r\n");
      out.write("                error: function(xhr, status, error) {\r\n");
      out.write("                    console.error(\"An error occurred: \" + error);\r\n");
      out.write("                    $('#searchResults').empty();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        } else {\r\n");
      out.write("            $('#searchResults').empty();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>         \r\n");
      out.write("         \r\n");
      out.write("\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/blog/mydiary.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cpath");
      // /WEB-INF/views/blog/mydiary.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/blog/mydiary.jsp(7,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/blog/mydiary.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("awsPath");
      // /WEB-INF/views/blog/mydiary.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/blog/mydiary.jsp(8,0) 'https://daydayday.s3.ap-northeast-2.amazonaws.com/day'",_jsp_getExpressionFactory().createValueExpression("https://daydayday.s3.ap-northeast-2.amazonaws.com/day",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/blog/mydiary.jsp(99,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty mvo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                      <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/follow\">구독</a></li>\r\n");
          out.write("                   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/blog/mydiary.jsp(103,18) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty mvo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li class=\"nav-item dropdown\" is=\"startBtn\">\r\n");
          out.write("                           <a id=\"startbtn\" class=\"nav-link dropdown-toggle\" href=\"#about\" role=\"button\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
          out.write("                              시작하기\r\n");
          out.write("                           </a>\r\n");
          out.write("                       <ul class=\"dropdownBox dropdown-menu\" aria-labelledby=\"dropdownMenuLink\" id=\"goWrite\">\r\n");
          out.write("                         <li><a class=\"dropdown-item\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/edit/in\">글쓰기</a></li>\r\n");
          out.write("                         <li><a class=\"dropdown-item\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/editphoto\">스티커 만들기</a></li>\r\n");
          out.write("                       </ul>                        \r\n");
          out.write("                        </li>                             \r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/blog/mydiary.jsp(129,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty mvo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li class=\"nav-item\"><a class=\"nav-link log-cl\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login/logoutProcess\">LOGOUT</a></li>\r\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/blog/mydiary.jsp(132,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty mvo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li class=\"nav-item\"><a class=\"nav-link log-cl\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login/in\">LOGIN</a></li>\r\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/blog/mydiary.jsp(162,22) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty mvo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(' ');
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/blog/mydiary.jsp(215,21) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("vo");
      // /WEB-INF/views/blog/mydiary.jsp(215,21) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/blog/mydiary.jsp(215,21) '${diary}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${diary}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                        <li class=\"item\">\r\n");
            out.write("                           <div class=\"itemCon\">\r\n");
            out.write("                              <div class=\"area_thumb_with_dropdown\">\r\n");
            out.write("                                 <div class=\"area_thumb\">\r\n");
            out.write("                                    <a class=\"section-link diaryIdx\" onclick=\"getBoard(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.diary_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\" href=\"#\" data-section=\"tempStorage\">\r\n");
            out.write("                                       <img class=\"thumb\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/cover/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.diary_cover}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                    </a>\r\n");
            out.write("                                 </div>\r\n");
            out.write("                                 <div id=\"dropdown-div\">\r\n");
            out.write("                                     <button class=\"dropdown-toggle morebtn\" type=\"button\" data-toggle=\"dropdown\"><img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/img/more2.png\"></button>\r\n");
            out.write("                                    <div class=\"dropFrm dropdown-menu\" style=\"min-width:0;\">\r\n");
            out.write("                                      <a class=\"dropItem\" onclick=\"modify(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.diary_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\" data-toggle=\"modal\" data-target=\"#makeDiary\" href=\"#\">수정</a>\r\n");
            out.write("                                      <a class=\"dropItem\" href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/myblog/diaryDelete?idx=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.diary_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">삭제</a>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                 </div>\r\n");
            out.write("                              </div>\r\n");
            out.write("                           </div>\r\n");
            out.write("                           <div class=\"area_text\">\r\n");
            out.write("                              <a class=\"section-link diaryIdx\" onclick=\"getBoard(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.diary_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\" href=\"#\" data-section=\"tempStorage\"><span class=\"title ell\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.diary_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></a>\r\n");
            out.write("                           </div>\r\n");
            out.write("                        </li>\r\n");
            out.write("                     ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
